version: '3'
services:
  portfolio:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.dev
